server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: Mysql@2711
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  instances:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8443/eureka

